version: '3.4'

services:
  samplesoap:
    image: ${DOCKER_REGISTRY-}samplesoap
    build:
      context: .
      dockerfile: SampleSoap/Dockerfile

  samplerest:
    image: ${DOCKER_REGISTRY-}samplerest
    build:
      context: .
      dockerfile: SampleRest/Dockerfile


  sampleodata:
    image: ${DOCKER_REGISTRY-}sampleodata
    build:
      context: .
      dockerfile: SampleOData/Dockerfile


  samplegraphql:
    image: ${DOCKER_REGISTRY-}samplegraphql
    build:
      context: .
      dockerfile: SampleGraphQL/Dockerfile

  postgresdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

volumes:
  portainer_data:
  postgres_data:
  pgadmin_data: